### ISSUE TITLE
Question about edge weight

### ISSUE THREAD

**Issue by elichienxD** [aizeny/snj#1]
Hi @NoahAmsel @aizeny ,

Thanks for making your code public and with good documentation. I'm very interested in your algorithm. I wonder if your SNJ method can support "weighted" version of tree output like traditional NJ? More specifically, the current output by SNJ is the unweighted one (or say, all weights = 1) and I wonder if it is possible to make it output non-negative weights for each edges?

Thanks,
Eli

**Comment by aizeny** [comment]
Hi @elichienxD ,
Thank you for your interest.
The current implementation does not support returning estimated weights. While it is possible to add this to the algorithm, we do not know when we will be able to add it.

Best,
Yariv

**Comment by elichienxD** [comment]
I see. Thanks for your timely reply!

Best,
Eli
